version: '3.8'

services:
  hitstv-bot:
    image: ghcr.io/hiizun/hitstv-bot:latest
    container_name: hitstv-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      DEVELOPER_ID: ${DEVELOPER_ID}
      RADIO_STREAM_URL: ${RADIO_STREAM_URL}
      RADIO_STATUS_URL: ${RADIO_STATUS_URL}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production

